version: '3.0'

volumes:
    sqlvolume:
        driver: local

networks:
    ocelot-network:
        driver: bridge

services:
    ocelot-gateway:
        environment:
            - "ASPNETCORE_ENVIRONMENT=Development"
            - "ASPNETCORE_URLS=http://+:80"
        ports:
            - "5000:80"
        container_name: ocelot-gateway
        image: ocelot-gateway
        build:
            context: .
            dockerfile: src/Poc.Ocelot.Gateway/Dockerfile
        networks:
            - ocelot-network
        depends_on:
            - sql-database

    accounts-service:
        environment:
            - "ASPNETCORE_ENVIRONMENT=Development"
            - "ASPNETCORE_URLS=http://+:80"
        container_name: accounts-service
        image: accounts-service
        build:
            context: .
            dockerfile: src/Poc.Ocelot.Accounts/Dockerfile
        networks:
            - ocelot-network
        depends_on:
            - ocelot-gateway

    payment-service:
        environment:
            - "ASPNETCORE_ENVIRONMENT=Development"
            - "ASPNETCORE_URLS=http://+:80"
        container_name: payment-service
        image: payment-service
        build:
            context: .
            dockerfile: src/Poc.Ocelot.Payments/Dockerfile
        networks:
            - ocelot-network
        depends_on:
            - ocelot-gateway

    product-service:
        environment:
            - "ASPNETCORE_ENVIRONMENT=Development"
            - "ASPNETCORE_URLS=http://+:80"
        container_name: product-service
        image: product-service
        build:
            context: .
            dockerfile: src/Poc.Ocelot.Products/Dockerfile
        networks:
            - ocelot-network
        depends_on:
            - ocelot-gateway

    backoffice-service:
        environment:
            - "ASPNETCORE_ENVIRONMENT=Development"
            - "ASPNETCORE_URLS=http://+:80"
        container_name: backoffice-service
        image: backoffice-service
        build:
            context: .
            dockerfile: src/Poc.Ocelot.Backoffice/Dockerfile
        networks:
            - ocelot-network
        depends_on:
            - ocelot-gateway

    sql-database:
        environment:
            - SA_PASSWORD=@Abcd1234
            - ACCEPT_EULA=Y
        ports:
            - "1433:1433"
            - "1434:1434"
        container_name: sql-database
        image: mcr.microsoft.com/mssql/server:2019-CU13-ubuntu-20.04
        networks:
            - ocelot-network
        volumes:
            - sqlvolume
