// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Poc.Ocelot.Accounts.DataContexts;

namespace Poc.Ocelot.Accounts.Migrations
{
    [DbContext(typeof(AccountsContext))]
    [Migration("20200212040504_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Poc.Ocelot.Accounts.Models.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnName("Id_Account")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnName("CreatedAt_Account")
                        .HasColumnType("Datetime");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnName("Email_Account")
                        .HasColumnType("NVARCHAR(256)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnName("Password_Account")
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnName("UpdatedAt_Account")
                        .HasColumnType("Datetime");

                    b.HasKey("Id");

                    b.ToTable("Account");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8d47f6ea-7202-448c-ab56-125365e10562"),
                            CreatedAt = new DateTime(2020, 2, 12, 1, 5, 4, 354, DateTimeKind.Local).AddTicks(3652),
                            Email = "leaosomogyi@hotmail.com",
                            Password = "190142EF04881B893D77A5C76AD8EAA10272BB8F",
                            UpdatedAt = new DateTime(2020, 2, 12, 1, 5, 4, 354, DateTimeKind.Local).AddTicks(3652)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
